/* answers to basic join in mysql, not yet completed */

/* asian population */
SELECT SUM(CITY.POPULATION)
FROM CITY 
JOIN COUNTRY ON CITY.COUNTRYCODE = COUNTRY.CODE 
WHERE COUNTRY.CONTINENT = 'Asia';

/* african cities */
SELECT CITY.NAME
FROM CITY 
JOIN COUNTRY ON CITY.COUNTRYCODE = COUNTRY.CODE 
WHERE COUNTRY.CONTINENT = 'Africa';

/* average population of each continent */
SELECT COUNTRY.CONTINENT, FLOOR(AVG(CITY.POPULATION))
FROM CITY 
JOIN COUNTRY ON CITY.COUNTRYCODE = COUNTRY.CODE 
GROUP BY COUNTRY.CONTINENT;

/* the report  */
SELECT IF (GRADE<8, NULL, Name), Grade, Marks
FROM STUDENTS JOIN GRADES 
ON MARKS >= MIN_MARK AND MARKS <= MAX_MARK
GROUP BY GRADE DESC, NAME, MARKS ASC
