/* answers to basic join in mysql, not yet completed */

/* asian population */
SELECT SUM(CITY.POPULATION)
FROM CITY 
JOIN COUNTRY ON CITY.COUNTRYCODE = COUNTRY.CODE 
WHERE COUNTRY.CONTINENT = 'Asia';

/* african cities */
SELECT CITY.NAME
FROM CITY 
JOIN COUNTRY ON CITY.COUNTRYCODE = COUNTRY.CODE 
WHERE COUNTRY.CONTINENT = 'Africa';

/* average population of each continent */
SELECT COUNTRY.CONTINENT, FLOOR(AVG(CITY.POPULATION))
FROM CITY 
JOIN COUNTRY ON CITY.COUNTRYCODE = COUNTRY.CODE 
GROUP BY COUNTRY.CONTINENT;

/* the report  */
SELECT IF (GRADE<8, NULL, NAME), GRADE, MARKS
FROM STUDENTS JOIN GRADES 
ON MARKS >= MIN_MARK AND MARKS <= MAX_MARK
GROUP BY GRADE DESC, NAME, MARKS ASC

/* contest leaderboard */
SELECT HACC.HACKER_ID, HACC.NAME, SUM(SCORE)
FROM (
    SELECT HACKER_ID, CHALLENGE_ID, MAX(SCORE) AS SCORE 
    FROM SUBMISSIONS
    GROUP BY HACKER_ID, CHALLENGE_ID)J
JOIN HACKERS HACC ON J.HACKER_ID = HACC.HACKER_ID
GROUP BY HACC.HACKER_ID, HACC.NAME
HAVING SUM(SCORE) > 0
ORDER BY SUM(SCORE) DESC, HACC.HACKER_ID

/* top competitors */
SELECT SUBS.HACKER_ID, HACC.NAME
FROM SUBMISSIONS SUBS
    JOIN CHALLENGES C ON SUBS.CHALLENGE_ID = C.CHALLENGE_ID
    JOIN DIFFICULTY D ON C.DIFFICULTY_LEVEL = D.DIFFICULTY_LEVEL
    JOIN HACKERS HACC ON SUBS.HACKER_ID = HACC.HACKER_ID 
WHERE SUBS.SCORE = D.SCORE
GROUP BY HACC.HACKER_ID, HACC.NAME
HAVING COUNT(SUBS.HACKER_ID) > 1
ORDER BY COUNT(SUBS.HACKER_ID) DESC, SUBS.HACKER_ID

/* olliviander's inventory */
SELECT W.ID, P.AGE, W.COINS_NEEDED, W.POWER
FROM WANDS AS W INNER JOIN WANDS_PROPERTY AS P ON W.CODE = P.CODE
WHERE P.IS_EVIL = 0 AND W.COINS_NEEDED = 
    (SELECT MIN(COINS_NEEDED)
     FROM WANDS AS W1 INNER JOIN WANDS_PROPERTY AS P1 ON W1.CODE = P1.CODE
     WHERE W1.POWER = W.POWER AND P1.AGE = P.AGE)
ORDER BY W.POWER DESC, P.AGE DESC

/* challenges */
